POST http://localhost:3333/api/parking
Content-Type: application/json

{
  "plateVehicle":"CBA1234",
  "entryData": "{{$datetime rfc1123}}"
}
###

PATCH http://localhost:3333/api/parking/ABC9997
Content-Type: application/json

{
  "outputData": "{{$datetime rfc1123}}"
}

###
GET http://localhost:3333/api/parking
Content-Type: application/json

###
GET http://localhost:3333/api/parking/ABC9992
Content-Type: application/json